# Prometheus.yml - file
# This must be in the same directory as of docker-compose.yml file
# All file can be found on https://prometheus.io/docs/guides/cadvisor/

scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080
